# **********
# base stage
# **********
FROM almalinux:9 AS base

# Install necessary dependencies for NVM, Node.js, and development utilities
RUN dnf -y update && \
    dnf -y install wget git bash openssh-clients vim && \
    dnf clean all

# Install NVM (latest version)
ENV NVM_DIR=/root/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

# Install Node.js v22 using NVM
RUN bash -c ". $NVM_DIR/nvm.sh && nvm install 22 && nvm use 22 && nvm alias default 22"

# Export NVM and Node.js to PATH so they are available in future sessions
ENV PATH=$NVM_DIR/versions/node/v22.0.0/bin:$PATH

# Set the working directory inside the container
WORKDIR /app

# **********
# deps stage
# **********
FROM base AS deps

# Copy package.json and lockfiles
COPY package.json ./ 
COPY package-lock.json* yarn.lock* pnpm-lock.yaml* ./ 

# Install dependencies
RUN bash -c ". $NVM_DIR/nvm.sh && npm install"

# Disable Next.js telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# **********
# inter stage
# **********
FROM deps AS inter

# Copy the rest of the application files to the container
COPY . .

# Expose the application's port
EXPOSE 3000

# **********
# prod stage
# **********
FROM inter AS prod

# Build the application for production
RUN bash -c ". $NVM_DIR/nvm.sh && npm run build"

# Run the application in production mode
CMD ["npm", "start"]

# **********
# dev stage
# **********
FROM inter AS dev

# Expose the port that the application will run on
EXPOSE 3000

# Run migrations and seeders before starting the app
CMD bash -c ". $NVM_DIR/nvm.sh && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run dev"
